# Generated by Django 5.1 on 2024-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_address', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'canceled'), (1, 'pending'), (2, 'registered'), (3, 'confirmed'), (4, 'delivered'), (5, 'closed'), (6, 'returned')], default=1)),
                ('payment_code', models.IntegerField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('sending_date', models.DateTimeField()),
            ],
        ),
    ]
