# Generated by Django 5.1 on 2024-08-23 11:43

import django.db.models.deletion
import django_smalluuid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('hexcode', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.brand')),
                ('categories', models.ManyToManyField(related_name='brands', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault, unique=True)),
                ('title', models.CharField(unique=True)),
                ('slug', models.SlugField(default='')),
                ('features', models.JSONField(default=dict, verbose_name='features of product')),
                ('descriptions', models.TextField(verbose_name='descriptions of product')),
                ('discount', models.SmallIntegerField(default=0)),
                ('price', models.IntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('is_special', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='products.category')),
                ('color', models.ManyToManyField(to='products.color')),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cover', to='core.gallery')),
                ('gallery', models.ManyToManyField(to='core.gallery')),
            ],
        ),
    ]
